Updated Location Services
Honey4Groceries/Honey4Groceries pull request #40
Opened 2019-01-26 18:53 UTC by paulpan05

2019-01-26 21:23 UTC, paulpan05 reviewed
I don't know if the Info.plist additions are needed

2019-02-01 09:14 UTC, godwinpang requested changes

2019-02-01 09:14 UTC, godwinpang commented on Honey4Groceries/Sources/Services/LocationService.swift
> +
documentation please

2019-02-01 09:14 UTC, godwinpang commented on Honey4Groceries/Sources/Services/LocationService.swift
> +    func getLocation() -> Guarantee<CLLocation?> {
don't return nil, create an enum of errors and throw instead. for your reference

enum VideoError: Error {
    case invalidStart
    case invalidStop
    case nilInput
    case nilOutput
    case accessDenied
}

2019-02-01 09:14 UTC, godwinpang commented on Honey4Groceries/Sources/View Controllers/ViewController.swift
> +        print("Hello")
remove debug

2019-02-02 21:43 UTC, godwinpang requested changes

2019-02-02 21:43 UTC, godwinpang commented on Honey4Groceries/Sources/Services/LocationService.swift
>                  successfully with CLLocation
throws?

2019-02-02 21:43 UTC, godwinpang commented on Honey4Groceries/Sources/View Controllers/ViewController.swift
>              case CLLocationManager.PMKError.notAuthorized:
move this error to be inside LocationService

2019-03-17 01:53 UTC, godwinpang approved these changes

2026-04-14 05:23 UTC, closed without merging